### ISSUE TITLE
这些不小得逻辑是？

### ISSUE THREAD

**Issue by Alice-Girl** [navcat/almanac#2]
![8](https://user-images.githubusercontent.com/28971462/27269915-39a32a64-54ed-11e7-92d3-4ec5fd13f54a.jpg)

**Comment by Alice-Girl** [comment]
不擅长描述问题，就直接上图，尴尬

**Comment by navcat** [comment]
在index.html里面每个单元格的点击有事件的回调
`    /**
     * 单击某一天的事件
     */
    clickDay: function(elem){
      var _this = $(elem);
      console.log('阳历：' + _this.attr('data-year') + '年' + _this.attr('data-month') + '月' + _this.attr('data-solor'));
    }`
这样可以实现单次点击事件右边的展示

同样的有一个回调
`afterDrawCld: function(year, month){
      // console.log('加载-调用回调函数 完成');
    }`
在这里，每翻一页，会回调一下，你可以写一个ajax请求去后台取当月的数据，然后填充上去就好了

**Comment by Alice-Girl** [comment]
Thank you

**Comment by Alice-Girl** [comment]
还有个问题请教下前辈，这个日历在同一个页面中可以重复调用吗？如上图：设计验证平台和仿真验证平台是同样的日历？可是插件中的Dom节点是ID.,,不晓得可以重复调用使用不？要是可以的话，那么要如何实现的呢？

**Comment by navcat** [comment]
可以的，HTML你贴两份就可以了，指定不同的ID，后面调用的时候 $("#id_almanac").almanac({})，根据这个ID调用就行了

**Comment by Alice-Girl** [comment]
你好，我又来叨扰，可以实现当前日期之前的不能点的功能吗
